sudo: false
dist: xenial
language: python
cache: pip
python:
- '3.7'
matrix:
  fast_finish: true
services:
- postgresql
- redis-server
addons:
  sonarcloud:
    organization: openexo
install: pip install -r requirements_test.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: tt8TY+X7gJd4alj73D+hgf57AZ2wHke6RyMkp0p9cdvOx3azv3V80T0cc4mFwR6DiEabxGgXUnKV5R6EGxA6JrxDuX9yGh8LF4vV1wHcr1yi2qoV5u1SeH8+ZeI8RxZOS//xUIkop6pV/GQx6YCTg+k9fHHuoC7NsIAmvoJ0FNU6HtZmKnGwoS8bkL50huQMu8klwCuTx/TYvopoLzlib3WTF1CB55O9M7SJ11dFk36dl+EAxeUkPQ2CBnVHsqVmudQqfCNOQ4j5rAdhhl1ROuh4UXGHBebNIS4pDLP9QOcwfQjPp8kFco9xa6lRfdlJ0hyvrqjtkT8N0bewvZeevR7JTDp5AsH2P+pS+RpTWV2TgFMHhbHg2eR/Q+JwZ54vS/buh2A+DLu5Bb267OAOHkFeZBOkdD9kpWGZ1E3GEr0n2PdaOS8ZPzDiQxKhiwHn3ujbVpksBu69J6h5ALl4Im6cwabTiYKG8u6kFO8xjdelgaeTUFVtzh3EV+pJSVBf8SwLsM/9qqKSHEGDsXNbAXrscdLTpObpgGYPC8mKUgKBmIg9mcE2JBoOtmlcCFQlSGzCM4NqswBQu0vpcu9dQt9OOsXMasCKGI+mZjZiL3PpOX19a6cXI+vTLJ4Uw2x/DLyBMyL86/7nQ6YBy9VOTWVAqnTLwKKchuA81oYCoqo=
  on:
    tags: true
    repo: exolever/django-earlyparrot
    python: 3.7
after_success:
- codecov
