sudo: false
dist: xenial
language: python
cache: pip
python:
  - "3.7"
matrix:
  fast_finish: true
services:
- postgresql
- redis-server
addons:
  sonarcloud:
    organization: openexo
install: pip install -r requirements_test.txt
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: IIK5s0tujcR85jiL0xHTqsq5wsjHV4eagx3aJwVQObOmRay8/Gif/ztvP350hGh153H2cUI7iOXNYDKnftSA0Z0dtjfdLcFmsYDjMcawL+lNulzcPz7w6VDncAEgwUgIQZywLe5R5zc9OZtfM6SPw2QKrvG9mIzZ7ZavU4NhlSdvkyC5WpI6/Dk4jOlWicIhObI+qhTDQmFdwCKFP4hoHBnrCcVrQ7tVTfZ/nKnl4SMh+w2pa/5iXfODftxezduK+bpewWxEi+5skORpu4cbP5wA3Py7raJ3z3tXfMX7Ize2gaSgDD9AaMIKNOhXfZVnW3wQNa5QwV0pQ2+IJZJkFxM85QVTC5l9WjgrKTVNpBQ5tDd0GL3FnyntA9UYtNL5iGnh6orqeiFcYXlWyDFq7ybtWO1SFrwe7utAHhbRGTgzmWuSZ72XVJ7stj7fzkV6Fy9BPc6U4vypYu2m2OB4tA0URzdjHVFVRLdx55C5G4d7sw/m5oo0dcCp5oJBVrdVEeAChALQ0iT3NQdCqJWOejx5o4ZjYqVxZCBEXF46aVL6odqkQguO5bqbLcZ0EcVUDiEYkavULSpl/tNZuU3NnsT0VDH/NvZVHBYI3Ak29HmikgBAJEPC0KaHBSyISnfYF/WcUqFFy1NicuoqSB1AG/jBU9hEIYwvNhQhC/htqME=
  on:
    tags: true
    repo: exolever/django-earlyparrot
    python: 3.7
after_success:
- codecov
